[package]
name = "insight-trading"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yahoo-finance = "0.3.0"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3.28"
time-format = "1.1.2"
